name: New Repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - run: |
          ./make-this-mine.sh && rm ./.github/workflows/on-new-repo.yml && rm ./make-this-mine.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Make this mine
          branch: master
